### ISSUE TITLE
Incorrect Detection of dGPU (Laptops)

### ISSUE THREAD

**Issue by dreamsyntax** [SandeMC/GTAIVSetupUtilityWPF#1]
While running the tool on laptop with dGPU, incorrectly will only find iGPU, even if Windows is set to run tool in context of dGPU.

This leads to the launch option message never appearing, so VRAM will be incorrectly set to 512mb

![image](https://github.com/SandeMC/GTAIVSetupUtilityWPF/assets/14857235/d4e970aa-b7ca-465f-a435-6d463d7d031e)
![image](https://github.com/SandeMC/GTAIVSetupUtilityWPF/assets/14857235/397a9318-c1e6-4d0e-af6f-837dcce6c1d2)

**Comment by SandeMC** [comment]
What gpu you run it with shouldn't play a role - the app checks every GPU with Vulkan support, or it should anyway. Can you provide me with values from the info button?

Could you also check if the same occurs on the Python version?

**Comment by dreamsyntax** [comment]
> What gpu you run it with shouldn't play a role - the app checks every GPU with Vulkan support, or it should anyway. Can you provide me with values from the info button?
> 
> Could you also check if the same occurs on the Python version?

![image](https://github.com/SandeMC/GTAIVSetupUtilityWPF/assets/14857235/1ec48395-50c2-4512-9bbe-e7254e0baacb)

For python version, what do you need?

**Comment by SandeMC** [comment]
> > What gpu you run it with shouldn't play a role - the app checks every GPU with Vulkan support, or it should anyway. Can you provide me with values from the info button?
> > 
> > Could you also check if the same occurs on the Python version?
> 
> ![image](https://github.com/SandeMC/GTAIVSetupUtilityWPF/assets/14857235/1ec48395-50c2-4512-9bbe-e7254e0baacb)
> 
> For python version, what do you need?

Try installing DXVK via the python version, send me the logs after you're done

**Comment by dreamsyntax** [comment]
Python version detects 8g of video memory and properly finds both GPU and Vulkan 1.3 support, unlike WPF. Here is full output
![image](https://github.com/SandeMC/GTAIVSetupUtilityWPF/assets/14857235/d9ee2fb6-9812-47b4-bb5c-edfe15089ee8)

**Comment by SandeMC** [comment]
> Python version detects 8g of video memory, unlike WPF. Here is full output
> ![image](https://github.com/SandeMC/GTAIVSetupUtilityWPF/assets/14857235/d9ee2fb6-9812-47b4-bb5c-edfe15089ee8)
> 

Mm, the WPF version probably fails to check the other json or doesnt even try to acquire it. Will look into it later, contact me on discord for helping

**Comment by dreamsyntax** [comment]
I don't need assistance, I have it manually configured, just wanted to report to further improve the program. 
Thank you for all the work you put into making the AIO GTA IV guide!

**Comment by SandeMC** [comment]
> I don't need assistance, I have it manually configured, just wanted to report to further improve the program. 
> Thank you for all the work you put into making the AIO GTA IV guide!

Actually I don't either. I forgot I have another double-gpu laptop in the house, lol.

**Comment by SandeMC** [comment]
Fixed in https://github.com/SandeMC/GTAIVSetupUtilityWPF/commit/889d090e732653c98aabd47576620c3eb5e98f4f. Stupidly obvious typo, thanks for bringing my attention to this.
