### ISSUE TITLE
Main window doesn't load

### ISSUE THREAD

**Issue by HeckFinlay** [SandeMC/GTAIVSetupUtilityWPF#2]
I installed the 1.2.0.59 archive on a clean Steam install of GTA IV CE on Windows 10 22H2. Running the setup utility effectively does nothing, but the process remains in memory at 0% CPU usage and a short log file is generated.

GPU is an NVIDIA Geforce GTX 680MX which supports Vulkan 1.2.

[GTAIVSetupUtilityLog.txt](https://github.com/SandeMC/GTAIVSetupUtilityWPF/files/13298173/GTAIVSetupUtilityLog.txt)

**Comment by HeckFinlay** [comment]
2023-11-08 14:50:16.8537|INFO|GTAIVSetupUtilityWPF.MainWindow| Initializing the main window...
2023-11-08 14:50:17.4285|INFO|GTAIVSetupUtilityWPF.MainWindow| Main window initialized!
2023-11-08 14:50:17.4285|INFO|GTAIVSetupUtilityWPF.MainWindow| Initializing the vulkan check...
2023-11-08 14:50:17.4803|DEBUG|GTAIVSetupUtilityWPF.VulkanChecker| Running vulkaninfo on GPU0... If this infinitely loops, your GPU is weird!

**Comment by SandeMC** [comment]
Can you run this in your terminal/console? `vulkaninfo --json=0 --output data0.json`
If it succeeds, send the file here.

**Comment by HeckFinlay** [comment]
[data0.json](https://github.com/SandeMC/GTAIVSetupUtilityWPF/files/13298459/data0.json)

**Comment by SandeMC** [comment]
Are you certain you have up-to-date drivers installed? That file reports only 1.0.42 support. Which, by the way, thank you, I now have a format of the v1.0 file to adjust the code to.

**Comment by HeckFinlay** [comment]
So, NVIDIA's driver selection tool and Windows Device Manager had given me old drivers from 2017. Following a Steam thread, I updated to Game Ready Driver 425.31 (25.21.14.2531), but that still only supports Vulkan 1.1.9.7. Techpowerup.com claims the 680MX Mac version supports Vulkan 1.2.175 so I'll see if I can update further at some point.

However the setup utility now runs correctly. On launching I get the error about the failed vulkaninfo check and DXVK not being available, but I understand from TJGM's videos that I can install DXVK 1.10.3 instead.

Thanks for helping with this and for your excellent guide. I would have got nowhere fast on my own :-)

**Comment by SandeMC** [comment]
Can you send me the 1.1 vulkaninfo as well?

**Comment by HeckFinlay** [comment]
Oops, meant to include it, here you go:

[data0.json](https://github.com/SandeMC/GTAIVSetupUtilityWPF/files/13299183/data0.json)

**Comment by SandeMC** [comment]
Weird, the tool should be able to work with this file. I'll do a bit extra work on the tool later, thanks for the input!

Also my Optimization page has steps to update your drivers

**Comment by HeckFinlay** [comment]
Yw, and thanks, I'll check it out!

Edit: FYI NVCleaninstall actually selects a slightly older driver, 419.17. Also I had to do `vulkaninfo --json=0 --output data0.json > data0.json` to make it generate a file.

**Comment by SandeMC** [comment]
@HeckFinlay
Is the `> data0.json` required for the vulkan 1.1 or 1.0?

**Comment by SandeMC** [comment]
Either way, I hopefully fixed the issue in https://github.com/SandeMC/GTAIVSetupUtilityWPF/releases/tag/1.2.3.

**Comment by HeckFinlay** [comment]
> @HeckFinlay
> 
> Is the `> data0.json` required for the vulkan 1.1 or 1.0?

Both.
