### ISSUE TITLE
Executable does not run on latest Windows 11 Insider builds

### ISSUE THREAD

**Issue by Rems19** [SandeMC/GTAIVSetupUtilityWPF#4]
Hi,

The executable does not seem to run on my system (Windows 11, build 26016.1012).

Here is the crash report from the fiability report in windows :
```
Source
GTAIVSetupUtilityWPF

Résumé
Fonctionnement arrêté

Date
‎28/‎12/‎2023 17:54

Statut
Rapport envoyé

Description
Chemin d’accès de l’application défaillante :	C:\Users\remil\OneDrive\Documents\GTA IV\GTAIVSetupUtilityWPF.exe

Signature du problème
Nom d’événement du problème :	APPCRASH
Nom de l’application:	GTAIVSetupUtilityWPF.exe
Version de l’application:	1.3.2.0
Horodatage de l’application:	65310000
Nom du module défaillant:	KERNELBASE.dll
Version du module défaillant:	10.0.26016.1000
Horodateur du module défaillant:	5525a47f
Code de l’exception:	e0434352
Décalage de l’exception:	000000000009d1ca
Version du système:	10.0.26016.2.0.0.256.48
Identificateur de paramètres régionaux:	1036
Information supplémentaire n° 1:	45e2
Information supplémentaire n° 2:	45e278ca09287f6673f9dc18ef3dbf8b
Information supplémentaire n° 3:	ca52
Information supplémentaire n° 4:	ca5296aa965b6356ed0d0d0ad99a587e

Informations complémentaires sur le problème
ID de compartiment :	781a0049370d4a50c2a2ff37c1d63ceb (1342916253850156267)
```

I have no log file. If I can provide more info, I'm happy to do so.

**Comment by SandeMC** [comment]
I genuinely have no idea what's going on *here*

Also please get your stuff out of the OneDrive folder

**Comment by Rems19** [comment]
I was under the impression it was an external app and didn't need to be in the game folder.
I already tried to run it from inside the game folder just in case (C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto IV\GTAIV\GTAIVSetupUtilityWPF.exe) but had the same issue.
I tried launching it in admin mode, with and without compatibility mode.

I just built the executable from the tag 1.3.2 on my PC and it works. My guess is that my Windows version is too recent (I'm on the cancary channel of Windows).

EDIT: Correction, it only lauches if I launch it alongside the generated dll, and the "Open" button makes the app crash.

**Comment by SandeMC** [comment]
It doesn't have to be in the game folder, but having executable or actively read things on the OneDrive folder is bad practice. Either way, I really have no clue what's going on. Latest stable Windows 11 works fine.
![image](https://github.com/gillian-guide/GTAIVSetupUtilityWPF/assets/70141395/57741e32-ab1d-4e80-a619-90edd4a2e652)

I use the Publish feature in VS2019 for building the app for release, as it provides a unified executable.

**Comment by Rems19** [comment]
I got it to work by updating my VS2022 packages before rebuilding it. I think updating the toolchain could be a good idea.
Feel free to close the issue or keep it open as you prefer.

**Comment by SandeMC** [comment]
Got it. Will do later. I also got mistaken, I use 2022.

**Comment by SandeMC** [comment]
I replaced the executable on the latest release after updating all the tools I had. Does the issue persist?

**Comment by Rems19** [comment]
It doesn't, the latest executable works like a charm out of the box, thanks!
I renamed the issue for people that might have the same issue with older executables.
